apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {}
  template:
    metadata:
      name: 'root'
    spec:
      project: default
      destination:
        name: '{{.name}}'
        namespace: 'argocd'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      source:
        path: app-of-applicationset-deletion/appsets
        repoURL: 'https://github.com/irizzante/argocd-experiments.git'
        targetRevision: HEAD