source:
  repoURL: https://kyverno.github.io/kyverno
  targetRevision: "2.7.0"
  releaseName: kyverno
destination:
  namespace: kyverno
valueFiles:
  - $values/templatePatch/kyverno/values.yaml
clusters:
  dev:
    enabled: true
  uat:
    enabled: true
  prod:
    enabled: true
  in-cluster:
    enabled: true