apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-60'
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {}
  template:
    metadata:
      name: 'addon-{{.name}}-nginx'
    spec:
      project: default
      destination:
        name: '{{.name}}'
        namespace: 'nginx'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      sources:
        - repoURL: https://github.com/irizzante/argocd-experiments.git
          targetRevision: '{{.metadata.annotations.addons_repo_revision}}'
          ref: values
        - repoURL: 'https://kubernetes.github.io/ingress-nginx'
          chart: 'ingress-nginx'
          targetRevision: '4.11.0'
          helm:
            values: |
              controller:
                service:
                  type: ClusterIP