apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
  - clusters: {}
  template:
    metadata:
      name: 'root'
    spec:
      project: default
      source:
        path: app-of-applicationset-order/eventual-consistency/appsets
        repoURL: 'https://github.com/irizzante/argocd-experiments.git'
        targetRevision: HEAD
      destination:
        name: '{{name}}'
        namespace: 'argocd'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true