apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  # Create a matrix generator that will install all chart in all clusters
  - matrix:
      generators:
        # Get all clusters
      - clusters: {}
      - git:
          repoURL: https://github.com/irizzante/argocd-experiments.git
          revision: HEAD
          files:
          # Find all .argocd.yaml
            - path: 'templatePatch/**/.argocd.yaml'
          values:
            # Add enabled field if clusters.${name}.enabled = true
            # name comes from the cluster generator
            enabled: '{{ dig "clusters" .name "enabled" true . }}'
    selector:
      matchLabels:
        # Keep only the one which field enabled=true
        enabled: "true"
  template:
    metadata:
      name: '{{ .path.basename }}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .destination.namespace }}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - ServerSideApply={{ dig "syncPolicy" "syncOptions" "ServerSideApply" "true" . }}
          - CreateNamespace={{ dig "syncPolicy" "syncOptions" "CreateNamespace" "true" . }}
  templatePatch: |
    {{ if (dig "annotations" false .) }}
    metadata:
      annotations:
        {{- range $key, $value := .annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    {{- end }}
    spec:
      sources:
        - repoURL: https://github.com/irizzante/argocd-experiments.git
          targetRevision: '{{ dig "clusters" .name "valuesRevision" "HEAD" . }}'
          ref: values
        - repoURL: '{{ .source.repoURL }}'
          chart: '{{ dig "source" "chart" .path.basename . }}'
          targetRevision: '{{ dig "clusters" .name "chartRevision" .source.targetRevision . }}'
          helm:
            releaseName: '{{ dig "source" "releaseName" .path.basename . }}'
            ignoreMissingValueFiles: true
            valueFiles:
            {{- range $valueFile := .valueFiles }}
              - {{ $valueFile }}
            {{- end }}